server:
  port: ${BACKEND_SERVER_PORT:9090}
  address: ${BACKEND_SERVER_ADDRESS:127.0.0.1}

spring:
  application:
    name: zebra-proxy
  threads:
    virtual:
      enabled: true
  thread-executor: virtual
  servlet:
    multipart:
      enabled: true
      max-file-size: ${BACKEND_UPLOAD_MAX_FILE_SIZE:16MB}
      max-request-size: ${BACKEND_UPLOAD_MAX_REQUEST_SIZE:16MB}
  jpa:
    hibernate:
      ddl-auto: none

security:
  password-salt: ${SECURITY_HASHED_PASSWORD_SALT:changeit}
  token-secret-key: ${SECURITY_TOKEN_SECRET_KEY:a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6} #must be 32 bytes
  allowed-origins: ${SECURITY_ALLOWED_ORIGINS:*} # TODO -> Only for dev
  internal:
    username: ${SECURITY_INTERNAL_USERNAME:changeit}
    password: ${SECURITY_INTERNAL_PASSWORD:changeit}
  session:
    core-pool-update-size: ${SECURITY_SESSION_CORE_POOL_UPDATE_SIZE:6}

logbook:
  format:
    style: http
  httpclient:
    decompress-response: true

springdoc:
  api-docs:
    path: /docs/api-docs
    enabled: ${DOCS_ENABLED:false}
  swagger-ui:
    enabled: ${DOCS_ENABLED:false}

webdriver:
  chromedriver-path: ${WEBDRIVER_CHROMEDRIVER_PATH:}
  chrome-binary-path: ${WEBDRIVER_CHROME_BINARY_PATH:}
  load-timeout: ${WEBDRIVER_LOAD_TIMEOUT_MS:15000}
  extra-wait-ms: ${WEBDRIVER_EXTRA_WAIT_MS:3000}

worker:
  delay: ${WORKER_DELAY_SECS:30}


print:
  card:
    width: ${PRINT_CARD_WIDTH_INCH:2.170} #2.125
    height: ${PRINT_CARD_HEIGHT_INCH:3.425} #3.370
    invert-media-orientation: ${PRINT_CARD_INVERT_MEDIA_ORIENTATION:false}
    invert-pageformat-orientation: ${PRINT_CARD_INVERT_PAGEFORMAT_ORIENTATION:false}