#  AUTHENTICATION
#Email change
mail.email_change.title=Your email was changed
mail.email_change.description=You''re receiving this message because your account''s email was successfully changed to {0}. If you didn''t request any change, please contact us
#Password reset
mail.password_reset.title=Reset password
mail.password_reset.description=Click the following link to reset the password of your account:
mail.password_reset.advise=If you didn't request a password reset, you can simply ignore this email.
#Password changed
mail.password_changed.title=The password of your account has been changed
mail.password_changed.description=Hi {0},<br>\
  if you haven't changed your password, please contact us and use the <i>reset password</i> form to get your account back.
#Account disabled
mail.too_many_login_attempts.title=Your account was disabled
mail.too_many_login_attempts.description=Your account was disabled after too many failed login attempts.<br>\
  Please contact an administrator to re-enable it.